# playbook for all systems

- name: install packages
  apt: 
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
    - apache2
    - net-tools
  
- name: configure apache
  template: src=apache.j2 dest=/etc/apache2/conf-enabled/demo.conf
  tags:
    - apache_cfg

- name: restart apache
  service: 
    name: apache2
    state: restarted
