# playbook for all systems

- name: install apache
  apt: 
    name: apache2
  tags:
    - install_apache
  
- name: configure apache
  template: src=apache.j2 dest=/etc/apache2/conf-enabled/demo.conf
  tags:
    - apache_cfg

- name: restart apache
  service: 
    name: apache2
    state: restarted
