# playbook for all systems

- name: Create hostfile
  template: src=motd.j2 dest=/etc/motd
  tags:
    - motd_config

- name: create systeminfo
  template: src=info.j2 dest=/tmp/sysinfo
  tags: 
    - create_sysinfo
